version: "3"

services:
  webserver:
    build:
      context: .
      dockerfile: dockerFile-php-apache
    container_name: webserver-boxbilling
    restart: unless-stopped
    tty: true
    ports: 
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:5.7.36
    container_name: db-boxbilling
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: boxbilling
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql/
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql:
    driver: local