FROM debian:stable-slim

RUN apt-get update && apt-get install -y apache2 php7.4 php7.4-mysql php7.4-curl php7.4-dom
RUN a2enmod rewrite
RUN a2enmod headers

RUN sed -i '/<Directory \/var\/www\/>/,/<\/Directory>/ s/AllowOverride None/AllowOverride All/' /etc/apache2/apache2.conf

CMD ["apachectl", "-D", "FOREGROUND"]